package in.lesuccess.portal.shared.sheets;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;

import java.util.concurrent.Executor;

/**
 * The one place a module hands a Sheets write to the background executor.
 *
 * <p>Modules call this from an AFTER_COMMIT transaction listener. Submission is
 * a queue offer and returns immediately, so the commit thread is never held for
 * network I/O — and if the queue is full, the executor's rejection handler
 * records the drop rather than losing it.</p>
 *
 * <p>The constructor is written out rather than generated by
 * {@code @RequiredArgsConstructor}: Lombok does not copy {@code @Qualifier} onto
 * the generated parameter without a {@code lombok.config} declaring it copyable,
 * and this project has none. Boot also auto-configures an
 * {@code applicationTaskExecutor} bean, so an unqualified {@code Executor}
 * injection point would be ambiguous — and if it resolved, it would silently
 * bypass the bounded pool this whole design depends on.</p>
 */
@Slf4j
@Component
@ConditionalOnProperty(name = "lesuccess.sheets.enabled", havingValue = "true")
public class SheetsSyncDispatcher {

    private final GoogleSheetsService sheetsService;
    private final SyncFailureRecorder failureRecorder;
    private final Executor sheetsSyncExecutor;

    public SheetsSyncDispatcher(GoogleSheetsService sheetsService,
                                SyncFailureRecorder failureRecorder,
                                @Qualifier("sheetsSyncExecutor") Executor sheetsSyncExecutor) {
        this.sheetsService = sheetsService;
        this.failureRecorder = failureRecorder;
        this.sheetsSyncExecutor = sheetsSyncExecutor;
    }

    public void submitAppend(SheetRow row) {
        sheetsSyncExecutor.execute(
                SheetSyncTask.append(sheetsService, failureRecorder, row));
    }

    public void submitStatusUpdate(SheetSpec spec, SyncEntityType entityType,
                                   Long entityId, String newStatus) {
        sheetsSyncExecutor.execute(
                SheetSyncTask.statusUpdate(sheetsService, failureRecorder, spec, entityType, entityId, newStatus));
    }
}
