package in.lesuccess.portal.shared.sheets;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.concurrent.Executor;

/**
 * Ensures every registered tab has its header row on startup.
 *
 * <p>Replaces the single hardcoded header bootstrap that used to live inside
 * GoogleSheetsService: each {@link SheetRowSource} now declares its own tab, so
 * a new module gets its header row for free.</p>
 *
 * <p><strong>Runs off the startup thread.</strong> {@code ApplicationReadyEvent}
 * listeners execute synchronously on the thread completing
 * {@code SpringApplication.run()}, so this walk — one network round trip per tab,
 * four tabs today — was wall-clock time added to every boot. Bounded timeouts
 * (see {@code GoogleSheetsConfig}) cap the worst case, but a Sheets endpoint that
 * is merely slow rather than hung still costs seconds per tab, every single dev
 * startup, for work nothing is waiting on.</p>
 *
 * <p>Nothing is waiting on it because the header row is self-healing:
 * {@link GoogleSheetsService#appendRow} and
 * {@link GoogleSheetsService#updateStatus} both call
 * {@link GoogleSheetsService#ensureHeaderRow} themselves before writing. A row
 * that commits while this is still in flight prepares its own tab. That is what
 * makes moving this off the startup thread safe rather than merely convenient —
 * without it, an append could land on an unlabelled sheet.</p>
 *
 * <p>Submitted to the existing {@code sheetsSyncExecutor} rather than a new pool
 * or {@code @Async}: it is the same bounded pool every other Sheets network call
 * already uses, and a second executor would mean two ceilings on one rate-limited
 * third-party API. The whole loop goes in as one task, not one per tab, so the
 * per-tab try/catch below stays exactly as it was and four startup tasks cannot
 * crowd the queue.</p>
 */
@Slf4j
@Component
@ConditionalOnProperty(name = "lesuccess.sheets.enabled", havingValue = "true")
public class SheetsHeaderInitialiser {

    private final GoogleSheetsService sheetsService;
    private final List<SheetRowSource> rowSources;
    private final Executor sheetsSyncExecutor;

    /**
     * Written out rather than generated by {@code @RequiredArgsConstructor} for
     * the same reason {@link SheetsSyncDispatcher} does: Lombok does not copy
     * {@code @Qualifier} onto the generated parameter without a
     * {@code lombok.config} declaring it copyable, and this project has none.
     * Boot also auto-configures an {@code applicationTaskExecutor}, so an
     * unqualified {@code Executor} injection point would be ambiguous — and if it
     * resolved, it would silently bypass the bounded pool.
     */
    public SheetsHeaderInitialiser(GoogleSheetsService sheetsService,
                                   List<SheetRowSource> rowSources,
                                   @Qualifier("sheetsSyncExecutor") Executor sheetsSyncExecutor) {
        this.sheetsService = sheetsService;
        this.rowSources = rowSources;
        this.sheetsSyncExecutor = sheetsSyncExecutor;
    }

    @EventListener(ApplicationReadyEvent.class)
    public void onApplicationReady() {
        log.info("Sheets: preparing {} tab(s) in the background", rowSources.size());
        sheetsSyncExecutor.execute(this::initialiseHeaderRows);
    }

    /**
     * Package-visible and synchronous so tests can drive it directly without an
     * executor. {@link #onApplicationReady()} is the only production caller.
     */
    void initialiseHeaderRows() {
        for (SheetRowSource source : rowSources) {
            SheetSpec spec = source.spec();
            try {
                sheetsService.ensureHeaderRow(spec);
                // ensureHeaderRow only hides columns on a tab it just created, so an
                // existing tab picks up a newly declared hidden column here.
                sheetsService.applyHiddenColumns(spec);
            } catch (Exception ex) {
                // Appends are unaffected by a missing header or a visible column, so a
                // failure here must not stop startup or the other tabs.
                log.error("Could not prepare sheet '{}'. Appends are unaffected; "
                        + "will retry on next startup.", spec.tabName(), ex);
            }
        }
    }
}
